version: '3'

services:
    back:
        container_name: back_infinalys2
        build:
            context: ./predictor
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        networks:
            - infinalys2
    front:
        container_name: front_infinalys2
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - infinalys2

networks:
    infinalys2:
